### ISSUE TITLE
What's going on with index.html?

### ISSUE THREAD

**Issue by Strangehill** [scotch-io/scotch-io.github.io#1]
How is it that the blog posts are rendered in the demo? It seems like the code in index.html has gone missing.

**Comment by whatnickcodes** [comment]
?

**Comment by Strangehill** [comment]
I see you replaced the contents of [index.html](https://github.com/scotch-io/scotch-io.github.io/blob/master/index.html) with  and the html still renders just fine. 
It seems all the work was being done by the default layout anyway.

**Comment by whatnickcodes** [comment]
The way I do the layouts, for the home page that code was irrelevant. Sorry for the confusion. I deleted it to make sure no one else is confused. Thanks
